# Generated by Django 5.1.6 on 2025-05-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HttpLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField()),
                ('method', models.CharField(max_length=10)),
                ('url', models.TextField()),
                ('protocol', models.CharField(max_length=20)),
                ('status_code', models.IntegerField()),
                ('size', models.PositiveIntegerField()),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('raw_log', models.TextField()),
                ('label', models.CharField(choices=[('normal', 'Normal'), ('path_traversal', 'Path Traversal'), ('sqli', 'SQL Injection'), ('xss', 'Cross-Site Scripting (XSS)'), ('command_injection', 'Command Injection')], default='normal', max_length=50)),
                ('risk_level', models.CharField(choices=[('normal', 'Normal'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50)),
                ('trained_at', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('scan_interval_seconds', models.PositiveIntegerField(default=60, help_text='Scan interval in seconds.')),
                ('batch_size', models.PositiveIntegerField(default=10, help_text='Number of logs to scan per interval.')),
                ('enabled', models.BooleanField(default=True, help_text='Enable or disable the scanning.')),
                ('alert_email', models.EmailField(blank=True, help_text='Email address to send alerts to.', max_length=254)),
                ('max_risk_level_to_alert', models.CharField(choices=[('normal', 'Normal'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='high', help_text='Trigger alerts for logs with this risk level or higher.', max_length=10)),
            ],
        ),
    ]
