# Generated by Django 5.1.6 on 2025-05-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='httplog',
            name='label',
            field=models.CharField(choices=[('normal', 'Normal'), ('path_traversal', 'Path Traversal'), ('sqli', 'SQL Injection'), ('xss', 'Cross-Site Scripting (XSS)'), ('command_injection', 'Command Injection')], default='normal', max_length=50),
        ),
        migrations.AlterField(
            model_name='httplog',
            name='risk_level',
            field=models.CharField(choices=[('normal', 'Normal'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10),
        ),
        migrations.AlterField(
            model_name='modelconfig',
            name='max_risk_level_to_alert',
            field=models.CharField(choices=[('normal', 'Normal'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='high', help_text='Trigger alerts for logs with this risk level or higher.', max_length=10),
        ),
    ]
